spring.application.name=gateway

monitoring-api.url=${MONITORING_API_URL:https://monitoring-api-1.onrender.com/api/v1}
monitoring-api.security.key=${MONITORING_API_KEY:zurgD6SwnioG1bcAHqnjBPdBSWDjw2GuzNQNzgaEMo82HJRseynjyFwJ9tDcXIyG}
jwt.secret=${SECRET:C4mUcRkqxwPZUcfc7hsRB0iayecJUAenSPBVuiGRlER}
feign.client.config.default.connectTimeout=10000
feign.client.config.default.readTimeout=30000
logging.level.feign=DEBUG
logging.level.org.springframework.cloud.openfeign=DEBUG