spring.application.name=gateway

#monitoring-api.url=${MONITORING_API:#{'http://localhost:8888/api/v1'}}
monitoring-api.url=${MONITORING_API:#{'https://monitoring-api-1.onrender.com/api/v1'}}
monitoring-api.security.key=${API_KEY:zurgD6SwnioG1bcAHqnjBPdBSWDjw2GuzNQNzgaEMo82HJRseynjyFwJ9tDcXIyG}
jwt.secret=C4mUcRkqxwPZUcfc7hsRB0iayecJUAenSPBVuiGRlER
